version: '3.7'

services:
  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: "service"
      POSTGRES_PASSWORD: "service"
      POSTGRES_DB: "baby-tracker"
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -d baby-tracker -U service"
      interval: 2s
      timeout: 5s
      retries: 10
